# Generated by Django 3.1.2 on 2020-10-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201024_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image1',
            field=models.ImageField(default=0, height_field='height', upload_to='', width_field='width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='image2',
            field=models.ImageField(default=0, height_field='height', upload_to='', width_field='width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='image3',
            field=models.ImageField(default=0, height_field='height', upload_to='', width_field='width'),
            preserve_default=False,
        ),
    ]
