# Generated by Django 3.1.2 on 2020-10-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201024_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='timestamp',
        ),
    ]
