# Generated by Django 3.1.2 on 2020-10-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201024_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='desc3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
