# Generated by Django 3.1.2 on 2020-10-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201028_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hero',
            new_name='team',
        ),
    ]
